"""Pydantic request and response schemas."""

from app.schemas.auth import (
    ProfileCreateRequest,
    ProfileResponse,
    ProfileUpdateRequest,
    TokenPayload,
)
from app.schemas.common import ErrorResponse, HealthResponse, MessageResponse
from app.schemas.farmer import (
    FarmCreate,
    FarmResponse,
    FarmUpdate,
    FarmerDashboardSummary,
    FarmerProfileCreate,
    FarmerProfileResponse,
    FarmerProfileUpdate,
    ProfileCompletionInfo,
)
from app.schemas.produce import (
    CropReferenceItem,
    ProduceCreate,
    ProduceImageReorderRequest,
    ProduceImageResponse,
    ProduceListResponse,
    ProduceResponse,
    ProduceSummaryStats,
    ProduceUpdate,
)

from app.schemas.admin import (
    AdminDashboardStats,
    FarmerVerificationDetailResponse,
    FarmerVerificationItem,
    FarmerVerificationListResponse,
    ProduceVerificationDetailResponse,
    ProduceVerificationItem,
    ProduceVerificationListResponse,
    VerificationDecisionRequest,
    VerificationRecordListResponse,
    VerificationRecordResponse,
    VerificationRejectRequest,
)

from app.schemas.address import (
    BuyerAddressCreate,
    BuyerAddressResponse,
    BuyerAddressUpdate,
)
from app.schemas.cart import (
    CartItemAddRequest,
    CartItemResponse,
    CartItemUpdateRequest,
    CartProductInfo,
    CartResponse,
)
from app.schemas.order import (
    BuyerOrderDetailResponse,
    BuyerOrderSummaryResponse,
    FarmerOrderDetailResponse,
    FarmerOrderItemResponse,
    FarmerOrderSummaryResponse,
    OrderCancelRequest,
    OrderCreateRequest,
    OrderItemResponse,
    OrderStatusHistoryResponse,
    OrderStatusUpdateRequest,
)

__all__ = [
    "HealthResponse",
    "ErrorResponse",
    "MessageResponse",
    "ProfileCreateRequest",
    "ProfileResponse",
    "ProfileUpdateRequest",
    "TokenPayload",
    "FarmerProfileCreate",
    "FarmerProfileUpdate",
    "FarmerProfileResponse",
    "FarmCreate",
    "FarmUpdate",
    "FarmResponse",
    "FarmerDashboardSummary",
    "ProfileCompletionInfo",
    "ProduceCreate",
    "ProduceUpdate",
    "ProduceResponse",
    "ProduceListResponse",
    "ProduceImageResponse",
    "ProduceImageReorderRequest",
    "ProduceSummaryStats",
    "CropReferenceItem",
    "AdminDashboardStats",
    "FarmerVerificationItem",
    "FarmerVerificationListResponse",
    "FarmerVerificationDetailResponse",
    "ProduceVerificationItem",
    "ProduceVerificationListResponse",
    "ProduceVerificationDetailResponse",
    "VerificationDecisionRequest",
    "VerificationRejectRequest",
    "VerificationRecordResponse",
    "VerificationRecordListResponse",
    "BuyerAddressCreate",
    "BuyerAddressUpdate",
    "BuyerAddressResponse",
    "CartItemAddRequest",
    "CartItemUpdateRequest",
    "CartProductInfo",
    "CartItemResponse",
    "CartResponse",
    "OrderCreateRequest",
    "OrderStatusUpdateRequest",
    "OrderCancelRequest",
    "OrderItemResponse",
    "OrderStatusHistoryResponse",
    "BuyerOrderSummaryResponse",
    "BuyerOrderDetailResponse",
    "FarmerOrderItemResponse",
    "FarmerOrderSummaryResponse",
    "FarmerOrderDetailResponse",
]
